### ISSUE TITLE
Help in getFromString() ,getFromInputStream ()

### ISSUE THREAD

**Issue by kunalgharate** [BigBadaboom/androidsvgsampleapp#2]
how its work please update the sample with direct pass data to getfromstring and GetFromInputStrean 

I have SVG path and I wanna convert a path to SVG

**Comment by BigBadaboom** [comment]
What are you stuck on?

There is documentation for AndroidSVG [here](http://bigbadaboom.github.io/androidsvg/documentation.html)


> I have SVG path and I wanna convert a path to SVG

Do you mean you have just the path description (`"M 0,0 L 100,50"` etc), and you want to render it?

In the next release there will be a new method to parse a path description.

    android.graphics.Path  parsePath(String pathdef)

But it returns a `android.graphics.Path` object, not an SVG.

**Comment by kunalgharate** [comment]
yes, I have a path I have to convert it into SVG.

w3schools.com/graphics/svg_path.asp

please see it. 

thank you for response

nice work sir Ji

**Comment by BigBadaboom** [comment]
I don't understand what you want to do.  I don't know what you mean by "I
have a path I have to convert it into SVG."

Do you mean that you have an SVG.  And you want to display it in your app?


Paul

**Comment by Viraj7009** [comment]
Hi @BigBadaboom thanks for this amazing library.  Is this  `parsePath(String pathdef)` method already added in release 1.5 and when is it being released. Thanks

**Comment by BigBadaboom** [comment]
Hi Viraj

Release 1.5  is coming soon.  I am actively working on the last few issues. You can [follow progress here](https://github.com/BigBadaboom/androidsvg/milestone/5).

**Comment by Viraj7009** [comment]
Thanks @BigBadaboom. I also wanted to ask you if its possible to align the svg's in different levels say for example of the US map where on level 1 it shows the states and svgs aligned for each state and if we zoom the map to level 2, each svg for state should be broken down into different counties for that state provided all the svg's are available for level 1 and level 2. I'm working on a project to achieve this but the level 2 alignment seems to be a problem. Could you please provide any insights you might have? Thanks

**Comment by BigBadaboom** [comment]
To avoid futher spamming the OPs email with unrelated messages, could you send your question to androidsvgfeedback@gmail.com please?  I will be happy to help you there.

**Comment by BigBadaboom** [comment]
Closing. No response from original poster for six months. It's unclear what they are requesting.
